version: '3.8'

services:
  notification_service:
    container_name: notification_service
    build: .
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
    env_file:
      - .env
    depends_on:
      - redis
      - db

  db:
    container_name: db
    image: postgres:15
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notification

  redis:
    container_name: redis
    image: redis:7-alpine

  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A app.main.celery worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - notification_service
      - redis
      - db

  celery_beat:
    container_name: celery_beat
    build: .
    command: celery -A app.main.celery beat -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - notification_service
      - redis
      - db

  flower:
    container_name: celery_flower
    build: .
    command: celery -A app.main.celery flower --port=5555
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 5557:5555
    depends_on:
      - notification_service
      - redis
      - db
      - celery_worker
      - celery_beat

volumes:
  postgres-data:
